using NUnit.Framework;
using UnityEngine;
using static UnityEngine.InputSystem.LowLevel.InputStateHistory;

[CreateAssetMenu(fileName = "NewScrapData", menuName = "Scrap Data", order = 1)]
public class ScrapScriptable : ScriptableObject
{
    public int relStatsCount;
    public string scrapName;
    public int scrapId;
    public int scrapRarity;
    public int scrapType;
    public string description;
    public string statsDescPos;
    public string statsDescMid;
    public string statsDescBad;
    public float fireSpeed;
    public bool fireSpeedRel;
    public int bulletDamage;
    public bool bulletDamageRel;
    public int accuracy;
    public bool accuracyRel;
    public int magSizeAdd;
    public bool magSizeAddRel;
    public int magSizeMult;
    public bool magSizeMultRel;
    public float reloadSpeed;
    public bool reloadSpeedRel;
    public int health;
    public bool healthRel;
    public int healthRecharge;
    public bool healthRechargeRel;
    public int movementSpeed;
    public bool movementSpeedRel;
    public int damageResistance;
    public bool damageResistanceRel;
    public int ability;
    public bool abilityRel;
    public int weakSpot;
    public bool weakSpotRel;
    public int critChance;
    public bool critChanceRel;
    public float dodgeChance;
    public bool dodgeChanceRel;
    public string extraInfo;
    public bool extraInfoRel;
    public float effectTime;
    public bool onEnemy;
    public bool whileReload;
    public bool onGetHit;
    public bool onKillEnemy;
    public bool diminishing;
    public string diminishStat;
    public float diminishMax;
    public int secondary;
    public bool secondaryRel;
    public int mobilty;
    public bool mobiltyRel;
    public int core;
    public bool coreRel;
}
